name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install pandas
      run: pip install pandas
    - name: Fetch latest data
      run: |-
        curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data | jq .vaccination_data | \
        python -c "import sys; import pandas; pandas.read_json(sys.stdin.read()).to_csv('current_daily_data.csv', index=False)"
        LAST_DATE=$(head -n2 current.csv | tail -n1 | cut -f1 -d','); cp current_daily_data.csv daily_data/${LAST_DATE}.csv
        awk '(NR == 1) || (FNR > 1)' daily_data/*.csv > vacc-timeseries.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
